### ISSUE TITLE
[Bug] Too many open files

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#202] opened 2017-10-24 13:42 UTC
I hit this bug when running on one of the RainCatcher repositories (the portal). Looks like we hit an upper limit, could be OS related but a quick search shows it's an issue with `fs` and alternatives are available:
https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

Just need a backoff strategy possibly. Full error is below and reproducible. 

```
(node:78160) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EMFILE: too many open files, open '/Users/lgriffin/GIT_testing/RainCatcher/raincatcher-portal/licenses/license.html'
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENFILE: file table overflow, open '/Users/lgriffin/GIT_testing/RainCatcher/raincatcher-portal/licenses/_MIT License.txt'
    at Error (native)
```

**Comment by helio-frota** [comment] 2017-10-24 14:21
@lgriffin Thanks for reporting this bug!
I'm using the raincatcher-portal locally to run the "functional-usage-test", but I can't reproduce.
I'll add much more dependencies to raincatcher-portal locally to see what happens.

**Comment by helio-frota** [comment] 2017-10-24 14:34
@lgriffin we are using graceful-fs now.
I can't reproduce on fedora because it seems to be a Mac issue or something.
In case the issue not solved we can reopen.
Thanks !
landed here: https://github.com/bucharest-gold/license-reporter/commit/b579daa81bfc21e4ef8294737bfa9ea67f9b9c47

**Closed by helio-frota** 2017-10-24 14:34 UTC
Labels: bug, in progress

**Comment by lgriffin** [comment] 2017-10-24 14:52
I just updated with your latest changes and it is still happening on my Macbook.

The XML generates fine and 40 text files are within the licenses folder (41 including the XML).

I get the following output:
`.....normal output snipped for brevity....
No URL was found for [BSD-3-Clause OR MIT]
No URL was found for [(WTFPL OR MIT)]
No URL was found for [(BSD-2-Clause OR MIT OR Apache-2.0)]
No URL was found for [(MIT AND CC-BY-3.0)]
No URL was found for [(MIT AND CC-BY-3.0)]
(node:80987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EMFILE: too many open files, open '/Users/lgriffin/GIT_testing/RainCatcher/raincatcher-portal/licenses/license.html'`

Will do some searching on this from an OSX perspective

**Comment by lgriffin** [comment] 2017-10-24 14:59
Solved it:
https://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os

Will update the readme to point to this for OSX users
